### ISSUE TITLE
Support for Segmentation

### ISSUE THREAD

**Issue by amitbcp** [DuaneNielsen/iic#1]
I was trying to replicate IIC for segmentation when I came across this implementation.
Does it support segmentation as well ?

**Comment by DuaneNielsen** [comment]
Sorry for the late reply.  This implementation only supports classification.  

However I can't think of any reason you couldn't re purpose the classifiers to do segmentation.

However, I suspect, that since the core of this algorithm is that it tries to fit a joint distribution for the data distribution, doing that for every pixel might be a bit expensive.  So you would probably need to do it in 2 steps.
